[http.middlewares]
[http.middlewares.cors-allow-post.headers]
accessControlAllowOriginList = ["*"]
accessControlAllowMethods = ["POST"]
accessControlAllowHeaders = [
  "Accept",
  "Content-Type",
  "Content-Length",
  "Accept-Encoding",
  "X-CSRF-Token",
]
addVaryHeader = true
