serverAddr = "vps.emdecloud.de" # TODO remove vps
serverPort = 7000

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

[[proxies]]
name = "traefik-http"
type = "tcp"
localIP = "traefik"
localPort = 80
remotePort = 80

[[proxies]]
name = "traefik-https"
type = "tcp"
localIP = "traefik"
localPort = 443
remotePort = 443

[[proxies]]
name = "minecraft-tcp"
type = "tcp"
localIP = "d578d980-534d-4d54-bea9-e208ff266475"
localPort = 25565
remotePort = 25565

[[proxies]]
name = "satisfactory-primary-tcp"
type = "tcp"
localIP = "b23c616f-a3c8-42b0-ad1e-1962139c7523"
localPort = 7777
remotePort = 7777

[[proxies]]
name = "satisfactory-primary-udp"
type = "udp"
localIP = "b23c616f-a3c8-42b0-ad1e-1962139c7523"
localPort = 7777
remotePort = 7777

[[proxies]]
name = "satisfactory-reliable-messaging-tcp"
type = "tcp"
localIP = "b23c616f-a3c8-42b0-ad1e-1962139c7523"
localPort = 8888
remotePort = 8888

[[proxies]]
name = "satisfactory-reliable-messaging-udp"
type = "udp"
localIP = "b23c616f-a3c8-42b0-ad1e-1962139c7523"
localPort = 8888
remotePort = 8888

[[proxies]]
name = "matrix-rtc-tcp"
type = "tcp"
localIP = "livekit-sfu"
localPort = 7881
remotePort = 7881

{{- range $_, $v := parseNumberRangePair "50100-50200" "50100-50200" }}
[[proxies]]
name = "matrix-rtc-udp-{{ $v.First }}"
type = "udp"
localIP = "livekit-sfu"
localPort = {{ $v.First }}
remotePort = {{ $v.Second }}
{{- end }}
