serverAddr = "vps.emdecloud.de"
serverPort = 7000

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

[[proxies]]
name = "traefik-http"
type = "tcp"
localIP = "traefik"
localPort = 80
remotePort = 80
# subdomain = "vps"
# customDomains = ["home.vps.emdecloud.de"]

[[proxies]]
name = "traefik-https"
type = "tcp"
localIP = "traefik"
localPort = 443
remotePort = 443
# subdomain = "vps"
# customDomains = ["home.vps.emdecloud.de"]

[[proxies]]
name = "minecraft-tcp"
type = "tcp"
localIP = "172.31.0.3"
localPort = 25565
remotePort = 25565

[[proxies]]
name = "satisfactory-primary-tcp"
type = "tcp"
localIP = "172.31.0.5"
localPort = 7777
remotePort = 7777

[[proxies]]
name = "satisfactory-primary-udp"
type = "udp"
localIP = "172.31.0.5"
localPort = 7777
remotePort = 7777

[[proxies]]
name = "satisfactory-reliable-messaging-tcp"
type = "tcp"
localIP = "172.31.0.5"
localPort = 8888
remotePort = 8888

[[proxies]]
name = "satisfactory-reliable-messaging-udp"
type = "udp"
localIP = "172.31.0.5"
localPort = 8888
remotePort = 8888
