# LiveKit SFU Configuration for MatrixRTC
# Based on: https://willlewis.co.uk/blog/posts/deploy-element-call-backend-with-synapse-and-docker-compose/

port: 7880
bind_addresses:
  - "0.0.0.0"

rtc:
  tcp_port: 7881
  port_range_start: 50100
  port_range_end: 50200
  use_external_ip: false

room:
  auto_create: false

logging:
  level: info

turn:
  enabled: false
  domain: localhost
  cert_file: ""
  key_file: ""
  tls_port: 5349
  udp_port: 443
  external_tls: true
