---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Project Pandora:
        - abbr: GH
          href: https://github.com/matthiasemde/Pandora
