---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- System:
  - Info:
      widget:
        type: glances
        url: http://glances:61208
        version: 4
        metric: info
  - CPU Usage:
      widget:
        type: glances
        url: http://glances:61208
        version: 4
        metric: cpu
  - Memory Usage:
      widget:
        type: glances
        url: http://glances:61208
        version: 4
        metric: memory
  - Services:
      widget:
        type: glances
        url: http://glances:61208
        version: 4
        metric: containers
  - CPU Temp:
      widget:
        type: glances
        url: http://glances:61208
        version: 4
        metric: sensor:Composite
  - Network Usage:
      widget:
        type: glances
        url: http://glances:61208
        version: 4
        metric: network:eth0
