---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Project Pandora
description: Landing page for Mattis und Thesis homelab
color: emerald

layout:
  System:
    style: row
    columns: 3
  Auto-Discovered1:
  Auto-Discovered2:
