---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    label: System
    cpu: true
    memory: true
    disk: /

- resources:
    label: Storage
    disk: /data

- search:
    provider: duckduckgo
    target: _blank
