name: Update Docker Image SHA256 Hashes

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-hashes:
    name: Update Docker SHA256 Hashes
    # Only run on PRs with titles starting with "chore(deps)"
    if: startsWith(github.event.pull_request.title, 'chore(deps)')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      
      - name: Update Docker image hashes
        id: update
        run: |
          set +e  # Don't exit on error, we want to check the exit code
          ./.github/scripts/update-docker-hashes.sh
          exit_code=$?
          set -e
          
          if [ $exit_code -eq 0 ]; then
            # Script exited with 0 = changes were made
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            # Script exited with non-zero = no changes needed
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.update.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add services/*/flake.nix
          git commit -m "chore: update Docker image SHA256 hashes"
          git push
